name: Github Secrets Deploy

on:
  push:
    branches:
      - main

jobs: 
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0 
        with:
          useConfigFile: true
          configFilePath: .github/version/version.yml

      - name: Create Tag
        run: | 
          git config --global user.name "Pieeer1"
          git config --global user.email "${{ secrets.PAT_EMAIL}}"
          git tag -a ${{ steps.gitversion.outputs.AssemblySemVer }} -m "Release ${{ steps.gitversion.outputs.AssemblySemVer }}"
          git push origin ${{ steps.gitversion.outputs.AssemblySemVer }}